- README.md
- lua/nvim-lsp-installer/server.lua
- lua/nvim-lsp-installer/servers/clangd.lua
This adds a basic clangd-11.0.0 server configuration for c, cpp and obj-c source files. 
I reckon there's some inner configuration that takes place thanks to `nvim-lspconfig` itself, as stated in the [documentation](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#clangd). 
Tested on Linux 5.11.10-arch1-1, but it should work fine for macOS as well. 
If I got anything wrong, I'm happy to fix it!
> added clangd server

- README.md
- lua/nvim-lsp-installer/server.lua
- lua/nvim-lsp-installer/servers/gopls.lua
This adds a basic gopls server configuration for Go source files. 
Since installing gopls requires the Go CLI, I thought that it would be better to avoid installing the CLI itself here, and it just aborts if Go isn't found in the system. Also, I don't think there's much control over the installation of the server itself, so `install_cmd` just checks if `gopls` exists afterwards. 
Tested on Linux 5.11.10-arch1-1, but it should work fine for other Go-supported systems as well.
If I got anything wrong, I'm happy to fix it!
(hello again! :))
> added gopls server

- README.md
- lua/nvim-lsp-installer/server.lua
- lua/nvim-lsp-installer/servers/texlab.lua
Hello, again!
This adds a basic texlab configuration to the plugin. Tested on linux, but should work fine on macOS as well. Technically, there are binaries for Windows too, but it seems virtually unsupported (but it wouldn't be too much of a hassle to add, if needed.)
Also, do you think a check for `tar` is needed?
P.S. Sorry for the logfile in gopls :P
> add texlab

- lua/nvim-lsp-installer/servers/hls/install.mjs
`${__dirname}` was exporting the location of the `Packer` installation folder, instead of the location of the Haskell language servers and `hls` script. This change fixes the issue for me.
> export proper location of haskell language servers

- README.md
- lua/nvim-lsp-installer.lua
- lua/nvim-lsp-installer/servers/diagnosticls/init.lua
This PR added support for [diagnostic-languageserver](https://github.com/iamcco/diagnostic-languageserver), a general-purpose language server like efm.
> add diagnostic-languageserver

- lua/nvim-lsp-installer/opts.lua
- lua/nvim-lsp-installer/servers/vscode-langservers-extracted/init.lua
> vscode-langservers-extracted: use correct root dir when producing cmd path

- lua/nvim-lsp-installer.lua
Speeds up `require("nvim-lsp-installer")` from ~50ms to ~2ms, a 96% decrease (YMMV).
> lazily require servers for faster startup times

- lua/nvim-lsp-installer/log.lua
- lua/nvim-lsp-installer/notify.lua
- lua/nvim-lsp-installer/process.lua
- lua/nvim-lsp-installer/ui/display.lua
- lua/nvim-lsp-installer/ui/status-win/init.lua
Add a logger based on Plenary's log implementation.
I basically hijacked the notify function, so it's trivial to swap out the logger for a more sophisticated one, should you wish so.
--- 
_Note: It's up to you to decide on how to set the default log level._
> feat: add a logger based on plenary.log

- lua/nvim-lsp-installer/servers/vscode-langservers-extracted/init.lua
In my environment, it did not start properly without --stdio, so I added the argument.
> fix: Add `--stdio` to the argument of vscode-langservers-extracted

- lua/nvim-lsp-installer/fs.lua
- lua/nvim-lsp-installer/installers/composer.lua
- lua/nvim-lsp-installer/installers/gem.lua
- lua/nvim-lsp-installer/installers/go.lua
- lua/nvim-lsp-installer/installers/init.lua
- lua/nvim-lsp-installer/installers/npm.lua
- lua/nvim-lsp-installer/installers/pip3.lua
- lua/nvim-lsp-installer/installers/shell.lua
- lua/nvim-lsp-installer/installers/std.lua
- lua/nvim-lsp-installer/installers/zx.lua
- lua/nvim-lsp-installer/server.lua
- lua/nvim-lsp-installer/servers/angularls/init.lua
- lua/nvim-lsp-installer/servers/clangd/init.lua
- lua/nvim-lsp-installer/servers/erlangls/init.lua
- lua/nvim-lsp-installer/servers/ltex/init.lua
- lua/nvim-lsp-installer/servers/vala_ls/init.lua
Currently the installation process can be broken down into these steps:
1. remove server root dir from fs, if it exists
2. recreate the server root dir
3. run the installation inside the server root dir
4. if installation fails, remove the server root dir
This is problematic for a couple reasons (see #154). This patch changes it to run in a tmpdir, and only
upon successful installation move it to the server's root dir:
1. create a new tmpdir
2. run the installation inside the tmpdir
3a. if installation fails, remove the tmpdir
3b. if installation succeeds, delete the server root dir if it exists, and move the tmpdir to the server root dir path
Resolves #154.
Todo
> run installations in tmpdir

- lua/nvim-lsp-installer/installers/context.lua
- lua/nvim-lsp-installer/installers/init.lua
- lua/nvim-lsp-installer/installers/pip3.lua
- lua/nvim-lsp-installer/server.lua
- lua/nvim-lsp-installer/servers/clangd/init.lua
- lua/nvim-lsp-installer/servers/vala_ls/init.lua
- lua/nvim-lsp-installer/ui/status-win/init.lua
This fixes issues with renaming py3 venv.
Fixes #223.
> pip3: promote install_dir to server's root dir immediately

- lua/nvim-lsp-installer/servers/jdtls/init.lua
At the moment lombok is downloaded to the LS directory but never used. This loads the plugin when loading the `jdtls`.
> Add lombok support #205

- lua/nvim-lsp-installer/servers/jdtls/init.lua
The issue is `--add-opens` and `--add-modules` are arguments to jvm. If we put them after the `-jar` option, they are passed to the java program, not the jvm. Similar fix was done in https://github.com/kabouzeid/nvim-lspinstall/pull/117
> moved add-opens and add-modules  java options before jar option

- lua/nvim-lsp-installer/servers/fsautocomplete/init.lua
This fixes issues on Windows (and prob more platforms) where
the shell command may fail but this is not captured by the
installer.
> fsautocomplete: don't use shell as an intermediary

- lua/nvim-lsp-installer/installers/pip3.lua
- lua/nvim-lsp-installer/settings.lua
Rather than hard-coding `python` or `python3`, just load the python3 that nvim knows about and let users override this setting. Since users probably already pass the checks in `:checkhealth` (ie. the python3 provider), this shouldn't be a big issue.
I'm stuck with python 2.7 on my machine (Blame Autodesk not updating their embedded python until *AFTER* python 2 was deprecated) so being able to explicitly set the executable path means I won't get stuck running Python 2 with the `python` call
> Get the python executable from settings instead of hard-coding it

- lua/nvim-lsp-installer/servers/lemminx/init.lua
- lua/nvim-lsp-installer/ui/state.lua
lemminx crashed when I tried to open a pom.xml with version 0.18.0-400, updating to 0.18.1-451 resolved the issue. I had this issue on Fedora 35, just for info.
> Update lemminx to 0.18.1-451 to resolve crash with maven files

- lua/nvim-lsp-installer/installers/std.lua
There's two packages that provide the `Expand-Archive`, (see https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/52). It can happen that the wrong `Expand-Archive` is chosen, resulting in an error. This fixes that.
> added explicit expand-archive command

- lua/nvim-lsp-installer/installers/std.lua
- lua/nvim-lsp-installer/servers/bicep/init.lua
This is done to avoid issues with unzipping the bicep-langserver.zip
on POSIX systems (see https://github.com/Azure/bicep/issues/3704).
Fixes #285.
> fix(bicep): download the langserver via the vscode distribution

- lua/nvim-lsp-installer/servers/powershell_es/init.lua
The [`PowerShellEditorServices`](https://github.com/PowerShell/PowerShellEditorServices) are cross-platform. This allows installing on more than just Windows.
Currently using this on Apple silicon.
> fix(powershell_es): don't limit to windows

- lua/nvim-lsp-installer/servers/angularls/init.lua
This seems to have broken in 18fa978dde6277617c269b726532eada9119988a, due to no more dependency deduplication.
> fix(angularls): fix --ngProbeLocation

- lua/nvim-lsp-installer/servers/zls/init.lua
See #329 for bug report: zls-0.2 change the archive format.
I'm new to the codebase so I'm not sure if this is the best way to implement the fix, but it's tested as working locally for me. Happy to make quick changes or close in favour of a different fix!
> fix: zls-0.2 uses a different archive path

- lua/nvim-lsp-installer/health/init.lua
The pattern `go(%d+)%.(%d+)%.(%d+)` can **only** be matched when the `go version` contains the patch number (e.g. go1.17.3).
In my case, the go version I installed is exactly `1.17`.
Before:
After:
Test result for the `go version` with/without patch number
```lua
string.find("go version go1.17 darwin/amd64", "go(%d+)%.(%d+)")
-- 12      17      1       17
string.find("go version go1.17.3 darwin/amd64", "go(%d+)%.(%d+)")
-- 12      17      1       17
```
> fix(health): ignore the patch number in capturing go version

- lua/nvim-lsp-installer/servers/zls/init.lua
The executable flag seems to have disappeared in 0.9.0.
> fix(zls): add chmod +x to binary

- lua/nvim-lsp-installer/jobs/outdated-servers/init.lua
- lua/nvim-lsp-installer/ui/status-win/init.lua
Previously it'd always update all installed servers. With this change it'll
only update servers that are outdated (defaults to all installed servers if
no servers are marked as outdated when triggered).
> ui: map keybind to update all outdated servers

- lua/nvim-lsp-installer/servers/angularls/init.lua
> fix(angularls): prepend cmd with 'cmd.exe /C' on Windows

- CUSTOM_SERVERS.md
- lua/nvim-lsp-installer/installers/go.lua
- lua/nvim-lsp-installer/servers/arduino_language_server/init.lua
- lua/nvim-lsp-installer/servers/efm/init.lua
- lua/nvim-lsp-installer/servers/gopls/init.lua
- lua/nvim-lsp-installer/servers/jsonnet_ls/init.lua
- lua/nvim-lsp-installer/servers/sqls/init.lua
This will update require go version 1.16 or newer. It uses `go install` instead of `go get` to install go packages.
Clarification from [go 1.16 release notes](https://tip.golang.org/doc/go1.16#modules):
> go install now accepts arguments with version suffixes (for example, go install example.com/cmd@v1.0.0). This causes go install to build and install packages in module-aware mode, ignoring the go.mod file in the current directory or any parent directory, if there is one. This is useful for installing executables without affecting the dependencies of the main module.
> go install, with or without a version suffix (as described above), is now the recommended way to build and install packages in module mode. go get should be used with the -d flag to adjust the current module's dependencies …
> Change go installer from get to install

- lua/nvim-lsp-installer/servers/omnisharp/init.lua
This PR will add support for omnisharp language srever that runs on .NET6.0 instead of mono, the support for .NET6.0 omnisharp came out in the release `1.38.0` and will replace the mono version as mentioned in this PR `https://github.com/OmniSharp/omnisharp-roslyn/pull/2291#issuecomment-985834029`
> add omnisharp net6.0 support instead of mono

- CUSTOM_SERVERS.md
As mentioned in #334, `lspconfig` recently changed the way configs are required. This updates the full example in custom server documentation.
> Fix configs require in custom server example

- lua/nvim-lsp-installer/servers/jdtls/init.lua
This will use the directory name of the resolved root_dir (`:h
lspconfig-root-dir`). If no root_dir is found (e.g. single file
mode), neovim's current directory is used.
Resolves #501.
> feat(jdtls): use the resolved workspace directory name as the -data directory

- lua/nvim-lsp-installer/servers/ansiblels/init.lua
Latest ansible-language-server fails on install with this line present.
the combination of `npm install` and `npm run compile` should be enough since `npm install` gets both the production and dev dependencies.  
`npm install --production` fails with missing typescript type definitions missing. 
```
node_modules/@nodelib/fs.scandir/out/providers/async.d.ts(1,23): error TS2688: Cannot find type definition file for 'node'.
node_modules/@nodelib/fs.scandir/out/providers/async.d.ts(4,45): error TS2503: Cannot find namespace 'NodeJS'.
node_modules/@nodelib/fs.scandir/out/types/index.d.ts(1,23): error TS2688: Cannot find type definition file for 'node'.
```
> remove npm install --production from ansiblels

- lua/nvim-lsp-installer/installers/context.lua
- lua/nvim-lsp-installer/platform.lua
- lua/nvim-lsp-installer/servers/rust_analyzer/init.lua
Resolves #514. `libc` lookup is now deferred into a function. Only major issue is that it relies on `ldd` which is not guaranteed to be installed, for instance on MacOS, but this is likely not an issue that will crop up as this is pointed more towards Linux with distributions that use `musl` instead of `glibc`.
> Support libc detection

- Makefile
- README.md
- doc/nvim-lsp-installer.txt
- lua/nvim-lsp-installer.lua
- lua/nvim-lsp-installer/middleware.lua
- lua/nvim-lsp-installer/server.lua
- lua/nvim-lsp-installer/servers/init.lua
- lua/nvim-lsp-installer/settings.lua
- tests/middleware_spec.lua
- tests/minimal_debug_init.lua
First step towards not requiring any special interactions in user's init scripts.
> feat: integrate with lspconfig's on_setup hook

- README.md
- doc/nvim-lsp-installer.txt
- lua/nvim-lsp-installer.lua
- lua/nvim-lsp-installer/middleware.lua
- lua/nvim-lsp-installer/settings.lua
This allows users to automatically install all servers that are setup via lspconfig.
> feat: add automatic_installation option to the setup table

- lua/nvim-lsp-installer/servers/beancount/init.lua
From the latest update from beancount-lsp repo, the owner didn't offer binary asset anymore. Instead, he recommended use cargo to install the server, check here (https://github.com/polarmutex/beancount-language-server#installation)
> fix!(beancount-language-server):update beancount install source

- lua/nvim-lsp-installer/servers/fortls/init.lua
switches to `fortls` from `fortran-language-server`.  `fortls` is a continuation of the `fortran-language-server` since it got abandoned ~2y ago. 
The name of the binary was chosen to be the same to allow VS Code, Atom and other editors to be easily backwards compatible without having to rewrite every extension. For that reason `fortls` and `fortran-language-server` cannot be simultaneously installed in a system, since the binary will be overwritten with whichever was installed last.
I also noticed that there is an autogenerated schema file: `fortls.lua` taken from the Fortran Intellisense VS Code extension that should preferably be deleted. That interface was problematic with the original `fortran-language-server` and is completly incompatible with `fortls` and the [Modern …
> Updates Fortran Language Server

- lua/nvim-lsp-installer/core/managers/pip3/init.lua
- lua/nvim-lsp-installer/core/spawn.lua
- tests/core/managers/pip3_spec.lua
- tests/core/spawn_spec.lua
This is primarily done to avoid cluttering the log file with a bunch of
ERROR entries. Also avoids unnecessary roundtrips to uv_spawn, I guess.
> fix(spawn): avoid spawning commands that aren't on PATH

- lua/nvim-lsp-installer/servers/solang/init.lua
This is now assumed to be installed on the system instead.
> refactor(solang): don't download llvm

- lua/nvim-lsp-installer/middleware.lua
- lua/nvim-lsp-installer/servers/pylsp/README.md
- lua/nvim-lsp-installer/servers/pylsp/init.lua
- lua/nvim-lsp-installer/servers/tflint/README.md
- lua/nvim-lsp-installer/servers/tflint/init.lua
This is not a desirable solution, but it's better than as-is.
There's a couple of reasons for this:
1) lspconfig only enables these commands upon successful attachment of
servers, which doesn't really fit their use case.
2) We gain direct access to new Lua APIs for defining user commands,
allowing us to leverage Lua callbacks and functions instead of
intermediary global variables.
> refactor: specify commands independently, not via lspconfig

- doc/nvim-lsp-installer.txt
- lua/nvim-lsp-installer.lua
- lua/nvim-lsp-installer/server.lua
- tests/middleware_spec.lua
All interactions from userland should preferably go through
require("nvim-lsp-installer").
> docs: remove nvim-lsp-installer.servers helptag

- lua/nvim-lsp-installer/servers/jdtls/init.lua
I read that the `-javaagent:...` needs to come before the `-jar` flag. Changing the order made `Lombok` work again.
> fix lombok not being recognized.

- lua/nvim-lsp-installer/servers/taplo/init.lua
Because the lsp is not the default feature in taplo, so need to add the feature
> fix the taplo with the upstream

- README.md
rnix has been add at #408, but readme has not updated.
> docs: add missing rnix in Available LSPs

- lua/nvim-lsp-installer/servers/texlab/init.lua
Updated the texlab server script: in the two most recent texlab releases a pre-built aarch64 server for macOS can be downloaded.
> fix(texlab): download aarch64 assets on arm macOS

- README.md
As noted [here](https://github.com/junegunn/vim-plug/issues/1074#issuecomment-791891919), `vim-plug` does not support double quotes for package names.
Since this is a silent failure i.e. it simply won't install the package, copying and pasting from the README almost made me pull my hair out :sweat_smile:
> docs: use single quotes for vim-plug installation instructions
