williamboman/nvim-lsp-installer

lua/nvim-lsp-installer/servers/eslintls.lua

eslintls: don't execute `tsc` via `npx`

---

doc/nvim-lsp-installer.txt
lua/nvim-lsp-installer.lua
lua/nvim-lsp-installer/server.lua

add get_server({server_name}) to public Lua API

---

lua/nvim-lsp-installer/servers/cssls/init.lua
lua/nvim-lsp-installer/servers/html/init.lua
lua/nvim-lsp-installer/servers/jsonls/init.lua
lua/nvim-lsp-installer/servers/vscode-langservers-extracted/init.lua

use vscode-langservers-extracted package

---

README.md
lua/nvim-lsp-installer.lua
lua/nvim-lsp-installer/installers/shell.lua
lua/nvim-lsp-installer/server.lua
lua/nvim-lsp-installer/servers/tflint/README.md
lua/nvim-lsp-installer/servers/tflint/init.lua

https://github.com/terraform-linters/tflint/pull/1184

add tflint

---

lua/nvim-lsp-installer/server.lua
lua/nvim-lsp-installer/servers/eslintls/init.lua

eslintls: defer registering server definition with lspconfig

---

lua/nvim-lsp-installer/servers/elixirls/init.lua

See the release notes for more information https://github.com/elixir-lsp/elixir-ls/releases/tag/v0.8.1
I tested this locally and everything seems to work as expected.

Update Elixir LS version to 0.8.1

---

CUSTOM_SERVERS.md
README.md
doc/nvim-lsp-installer.txt
lua/nvim-lsp-installer.lua
lua/nvim-lsp-installer/data.lua
lua/nvim-lsp-installer/dispatcher.lua
lua/nvim-lsp-installer/installers/go.lua
lua/nvim-lsp-installer/installers/init.lua
lua/nvim-lsp-installer/installers/npm.lua
lua/nvim-lsp-installer/installers/pip3.lua
lua/nvim-lsp-installer/installers/shell.lua
lua/nvim-lsp-installer/installers/zx.lua
lua/nvim-lsp-installer/log.lua
lua/nvim-lsp-installer/process.lua
lua/nvim-lsp-installer/server.lua
lua/nvim-lsp-installer/servers/init.lua
lua/nvim-lsp-installer/servers/tflint/init.lua
lua/nvim-lsp-installer/ui/display.lua
lua/nvim-lsp-installer/ui/init.lua
lua/nvim-lsp-installer/ui/state.lua
lua/nvim-lsp-installer/ui/status-win/init.lua
plugin/nvim-lsp-installer.vim

add direct integration with libuv instead of going through termopen, also implement a UI

---

lua/nvim-lsp-installer/installers/gem.lua
lua/nvim-lsp-installer/installers/go.lua
lua/nvim-lsp-installer/installers/npm.lua
lua/nvim-lsp-installer/installers/pip3.lua
lua/nvim-lsp-installer/installers/std.lua
lua/nvim-lsp-installer/servers/groovyls/init.lua
lua/nvim-lsp-installer/servers/texlab/init.lua

better error messages

---

lua/nvim-lsp-installer/installers/npm.lua

installers/npm: ensure local npm root dir before installing

---

.github/workflows/ci.yml
.styluaignore
lua/nvim-lsp-installer/dispatcher.lua
lua/nvim-lsp-installer/servers/texlab/init.lua

Hi I improve the CI for the lua files with stylua actions.

Improve the CI for the fmt

---

CUSTOM_SERVERS.md
README.md
doc/nvim-lsp-installer.txt
lua/nvim-lsp-installer.lua
lua/nvim-lsp-installer/log.lua
lua/nvim-lsp-installer/opts.lua
lua/nvim-lsp-installer/servers/init.lua
lua/nvim-lsp-installer/settings.lua
lua/nvim-lsp-installer/ui/status-win/init.lua
plugin/nvim-lsp-installer.vim

add Lua API to override default settings

---

doc/nvim-lsp-installer.txt
lua/nvim-lsp-installer/server.lua
lua/nvim-lsp-installer/servers/init.lua

server: add :on_ready() method

---

lua/nvim-lsp-installer/fs.lua
lua/nvim-lsp-installer/server.lua

colocate tmpdir with the server's install dir to avoid cross-fs issues

---

README.md
doc/nvim-lsp-installer.txt
lua/nvim-lsp-installer.lua
lua/nvim-lsp-installer/server.lua
plugin/nvim-lsp-installer.vim

server: add attach_buffers() method

---

lua/nvim-lsp-installer/server.lua

respect autostart setting

---

lua/nvim-lsp-installer/server.lua

fix attaching servers with no filetypes defined

---

README.md
lua/nvim-lsp-installer/_generated/filetype_map.lua
lua/nvim-lsp-installer/_generated/language_autocomplete_map.lua
lua/nvim-lsp-installer/_generated/metadata.lua
lua/nvim-lsp-installer/servers/fsautocomplete/init.lua
lua/nvim-lsp-installer/servers/init.lua

Add fsautocomplete language server for F#

add fsautocomplete LS for F#

---

lua/nvim-lsp-installer/_generated/filetype_map.lua
lua/nvim-lsp-installer/_generated/language_autocomplete_map.lua
lua/nvim-lsp-installer/_generated/metadata.lua
lua/nvim-lsp-installer/servers/esbonio/init.lua
lua/nvim-lsp-installer/servers/init.lua

This should be works. But lspconfig has no configuration for esbonio.
I had make a pr for it in lspconfig.
This esbonio should install just like this, but configurations are unknown. (It mean esbonio running but not work when I open rst file :) )
I'll communicate with esbonio's author as much as possible.

feat(servers): add esbonio for rst

---

lua/nvim-lsp-installer/servers/angularls/init.lua

Fixes #268.
I tried overloading it with an empty function but it didn't work.

angularls: overload on_new_config with new probe locations

---

lua/nvim-lsp-installer/installers/context.lua
lua/nvim-lsp-installer/installers/shell.lua
lua/nvim-lsp-installer/process.lua

fix(windows): unset PSMODULEPATH before invoking powershell scripts

---

README.md
lua/nvim-lsp-installer/_generated/filetype_map.lua
lua/nvim-lsp-installer/_generated/metadata.lua
lua/nvim-lsp-installer/servers/dartls/init.lua
lua/nvim-lsp-installer/servers/init.lua
scripts/autogen_metadata.lua

add dartls

---

lua/nvim-lsp-installer/servers/fsautocomplete/init.lua

fix fsharp

---

lua/nvim-lsp-installer/servers/eslint/README.md

Feel free to let me know what you would like changed to match your syntax/style.
I know the *NOTE* is obvious to most, but for noobies like me, it may not be. :)

Added some clarity to eslint readme

---

lua/nvim-lsp-installer/servers/angularls/init.lua

fix(angularls): also use new_root_dir for probe locations

---

README.md
doc/nvim-lsp-installer.txt

docs: clarify how servers are installed and the recommended setup

---

lua/nvim-lsp-installer/installers/shell.lua

fix(installers/shell): pass script via arg, when possible

---

lua/nvim-lsp-installer/servers/sumneko_lua/init.lua

sumneko_lua: don't provide -E argument as it's not needed

---

README.md
lua/nvim-lsp-installer/servers/pylsp/README.md
lua/nvim-lsp-installer/servers/pylsp/init.lua

#317
Try adding better documentation to install `pylsp` plugins using `nvim-lsp-installer`
I don't think it completely fixes the issue as it only add documentation, so it should not close the issue

add :PylspInstall command for managing 3rd party pylsp plugins

---

README.md
doc/nvim-lsp-installer.txt
lua/nvim-lsp-installer.lua
plugin/nvim-lsp-installer.vim

This will prompt the user which server associated with the currently opened
buffer's &filetype to install.

feat: allow server installation by just typing `:LspInstall`

---

lua/nvim-lsp-installer/servers/sumneko_lua/init.lua

fix(sumneko_lua): (breaking) support new archive structure

---

lua/nvim-lsp-installer/installers/context.lua
lua/nvim-lsp-installer/installers/init.lua
lua/nvim-lsp-installer/servers/ccls/init.lua

fix(ccls): (breaking) support more Linux distros

---

lua/nvim-lsp-installer/installers/context.lua
lua/nvim-lsp-installer/installers/init.lua
lua/nvim-lsp-installer/installers/std.lua
lua/nvim-lsp-installer/servers/ccls/init.lua

This is a breaking change due to fundamental changes to the
installer. Re-installation will be required.
Reolves #350.

fix(ccls): better Mac support

---

README.md
doc/nvim-lsp-installer.txt
lua/nvim-lsp-installer/settings.lua
lua/nvim-lsp-installer/ui/status-win/init.lua

(I'm spamming the keybind in the recording)
https://user-images.githubusercontent.com/6705160/147225943-3d4575ba-7a00-4ea6-955f-fa065eef8c00.mov

feat(ui): add keybind to update all installed servers

---

lua/nvim-lsp-installer/servers/taplo/init.lua

https://github.com/tamasfe/taplo/releases

fix(taplo): wrong github-release linux link (#389)

---

lua/nvim-lsp-installer/jobs/outdated-servers/init.lua
lua/nvim-lsp-installer/ui/status-win/init.lua

I think this gives a better cursory overview of what's happening, also tone down the usage of colors a bit
https://user-images.githubusercontent.com/6705160/148462955-b25fe4b1-d099-4843-912e-33c34a422e93.mov

fix(ui): less intrusive version check UI

---

lua/nvim-lsp-installer/core/clients/github.lua
lua/nvim-lsp-installer/core/fetch.lua
lua/nvim-lsp-installer/ui/status-win/init.lua

feat: integrate gh-cli for GitHub API calls

---

lua/nvim-lsp-installer/servers/ccls/init.lua

fix(ccls): default to system clang+llvm if no prebuilt dist exist for current OS/arch

---

lua/nvim-lsp-installer/core/receipt.lua
lua/nvim-lsp-installer/servers/julials/init.lua

- Format the script to a "Julia" style
- Remove some changes I made which are no longer needed

Format the script

---

lua/nvim-lsp-installer/servers/ccls/init.lua

fix(ccls/macos): append /lib/cmake to CMAKE_PREFIX_PATH

---

lua/nvim-lsp-installer/servers/volar/init.lua

fix(volar): vendor tsserver

---

.github/ISSUE_TEMPLATE/server_issue.yaml
tests/minimal_debug_init.lua

add server_issue.yml issue template

---

lua/nvim-lsp-installer/core/fetch.lua
lua/nvim-lsp-installer/installers/shell.lua

fix(powershell): set security protocol to TLS1.2

---

README.md
lua/nvim-lsp-installer/_generated/filetype_map.lua
lua/nvim-lsp-installer/_generated/metadata.lua
lua/nvim-lsp-installer/servers/init.lua
lua/nvim-lsp-installer/servers/slint_lsp/init.lua

https://slint-ui.com/ has the details to the language and LS implementation.
The binary is called slint_lsp (which is also the name in nvim-lspconfig), so I would like to keep that here as well.

Add slint language server for .slint files

---

.github/workflows/metadata-diff.yml
.github/workflows/run-autogen.yml
lua/nvim-lsp-installer/core/async/init.lua
scripts/autogen_metadata.lua
scripts/autogen_metadata.sh
tests/core/async_spec.lua
tests/core/process_spec.lua
tests/luassertx/lua/luassertx.lua
tests/server_spec.lua
tests/ui_spec.lua

More lightweight alternative of plenarys async module.

feat: add async module

---

lua/nvim-lsp-installer/core/async/spawn.lua
lua/nvim-lsp-installer/core/result.lua
lua/nvim-lsp-installer/jobs/outdated-servers/gem.lua
lua/nvim-lsp-installer/jobs/version-check/init.lua
lua/nvim-lsp-installer/process.lua
lua/nvim-lsp-installer/ui/status-win/init.lua
tests/jobs/outdated-servers/gem_spec.lua
tests/server_spec.lua

Resolves #510.
https://user-images.githubusercontent.com/6705160/156441021-62d049e1-6199-4db1-b286-fafa24726dd7.mov
The modules are getting a bit messy, will fix later.

feat(ui): display installed server version

---

lua/nvim-lsp-installer/servers/volar/init.lua

see https://github.com/johnsoncodehk/volar/issues/876
see https://github.com/johnsoncodehk/volar/blob/master/packages/vue-language-server/package.json#L2

chore(volar): update volar package name

---

lua/nvim-lsp-installer/servers/ansiblels/init.lua

fix(ansiblels): use correct command on Windows

---

README.md
lua/nvim-lsp-installer/_generated/filetype_map.lua
lua/nvim-lsp-installer/_generated/language_autocomplete_map.lua
lua/nvim-lsp-installer/_generated/metadata.lua
lua/nvim-lsp-installer/servers/init.lua
lua/nvim-lsp-installer/servers/prosemd_lsp/init.lua

add prosemd_lsp

---

lua/nvim-lsp-installer/core/fs.lua
lua/nvim-lsp-installer/core/installer/context.lua
lua/nvim-lsp-installer/core/spawn.lua
lua/nvim-lsp-installer/servers/r_language_server/init.lua
tests/core/spawn_spec.lua

fix(r_language_server): run install script via stdin

---

lua/nvim-lsp-installer/servers/r_language_server/init.lua

Co-authored-by: Samuel C-J Lee <chia-jung.l@outlook.com>

r_language_server: install languageserversetup via remotes::install_github

---

lua/nvim-lsp-installer/core/managers/github/init.lua

This is a solution for #624 .
I'm not sure if it's the real problem but it does solve my problem.

fix(rust-analyzer): unzip filename error

---

lua/nvim-lsp-installer/servers/arduino_language_server/README.md
lua/nvim-lsp-installer/servers/arduino_language_server/init.lua

This is now expected to be installed on the system instead.

fix!(arduino_language_server): dont install arduino-cli and clangd

---

lua/nvim-lsp-installer/core/managers/std/init.lua
lua/nvim-lsp-installer/core/receipt.lua
lua/nvim-lsp-installer/servers/hls/init.lua

fix(hls): download archive from downloads.haskell.org

---

lua/nvim-lsp-installer/ui/status-win/init.lua

ui: add clarifications around settings schema

---

lua/nvim-lsp-installer/servers/vala_ls/init.lua

fix(vls): fix meson -Dprefix path

---

README.md
doc/nvim-lsp-installer.txt
lua/nvim-lsp-installer/servers/hls/init.lua

@ThoNohT @black-desk does this improve things?

fix(hls): install via ghcup install

---

ftplugin/lspinfo.lua
lua/nvim-lsp-installer/core/functional.lua
tests/core/functional_spec.lua

feat: override :LspInfo's "cmd is executable" diagnostic message

---

lua/nvim-lsp-installer/core/ui/display.lua
lua/nvim-lsp-installer/core/ui/init.lua
lua/nvim-lsp-installer/ui/init.lua
tests/core/ui_spec.lua

because why not
also switch to lua keymaps & autocmds
https://asciinema.org/a/WvXgc5jeQFeNr8QiDQGMUmm5Z

feat(ui): use diagnostics to show some messages

---

lua/nvim-lsp-installer/core/managers/github/client.lua
lua/nvim-lsp-installer/health/init.lua

feat(health): check GitHub rate limit

---

lua/nvim-lsp-installer/core/managers/git/init.lua
lua/nvim-lsp-installer/core/managers/github/init.lua
lua/nvim-lsp-installer/servers/erlangls/init.lua
lua/nvim-lsp-installer/servers/quick_lint_js/init.lua

fix(erlangls): follow git tags

---

README.md
doc/nvim-lsp-installer.txt
lua/nvim-lsp-installer/core/managers/github/init.lua
lua/nvim-lsp-installer/settings.lua

feat(github): add setting to customize asset download url

---

lua/nvim-lsp-installer/core/ui/display.lua
lua/nvim-lsp-installer/ui/init.lua

ui: no borders & change heading style

---

lua/nvim-lsp-installer/servers/ltex/init.lua

feat(ltex): use platform independent dist if java is installed

---

lua/nvim-lsp-installer/core/managers/luarocks/init.lua
lua/nvim-lsp-installer/core/spawn.lua
lua/nvim-lsp-installer/health/init.lua
lua/nvim-lsp-installer/servers/teal_ls/init.lua
tests/core/managers/luarocks_spec.lua

feat(luarocks): use luarocks.bat executable if it's available

---

lua/nvim-lsp-installer/core/async/init.lua

These are otherwise completely silenced.

refactor(async): log errors that occur inside a.scope blocks

---

README.md
lua/nvim-lsp-installer/servers/julials/README.md
lua/nvim-lsp-installer/servers/julials/init.lua

fix(julials): improve environment detection and set JULIA_LOAD_PATH

---

README.md
doc/nvim-lsp-installer.txt
lua/nvim-lsp-installer.lua
lua/nvim-lsp-installer/core/ui/display.lua
lua/nvim-lsp-installer/settings.lua
lua/nvim-lsp-installer/ui/init.lua

feat(ui): add setting to customize window border

---

lua/nvim-lsp-installer/servers/marksman/init.lua

fix(marksman): fix platform check for Windows x64

---

lua/nvim-lsp-installer/health/init.lua

While a version lower than this is fine for most servers, there are
cases where version 1.60.0 or higher is required (taplo).

feat(health): ensure cargo version >= 1.60.0

---

README.md
doc/nvim-lsp-installer.txt

docs: update Usage section

---

lua/nvim-lsp-installer/servers/clojure_lsp/init.lua

This commit add support for aarch64 downloads on mac and linux for clojure-lsp

add support for aarch64 downloads for clojure-lsp

---

lua/nvim-lsp-installer/health/init.lua
lua/nvim-lsp-installer/middleware.lua

feat(health): detect and display unenhanced server configs

---

lua/nvim-lsp-installer/servers/arduino_language_server/init.lua

fix(arduino_language_server): fix Windows asset files

---

lua/nvim-lsp-installer/ui/init.lua

feat(ui): include links to mason.nvim and project status in header
